### ISSUE TITLE
Make sure heading remains consistent across all pages

### ISSUE THREAD

**Issue by tiemaeroquerre** [ericmeltzer/proofofwork#12]
The formatting and content of the heading should remain consistent page to page

**Comment by mingzhouyang** [comment]
Can you give a specific page?

**Comment by tiemaeroquerre** [comment]
Sure :) All the pages should look like the home page
<img width="856" alt="screen shot 2018-08-15 at 3 28 47 pm" src="https://user-images.githubusercontent.com/32519583/46617259-4f83dd00-caea-11e8-89c0-2ad258300351.png">
