### ISSUE TITLE
Change color of story titles from blue to black and unbold

### ISSUE THREAD

**Issue by tiemaeroquerre** [ericmeltzer/proofofwork#17]
Change color of story titles from blue to black and unbold

<img width="476" alt="screen shot 2018-10-08 at 11 28 29 am" src="https://user-images.githubusercontent.com/32519583/46618375-52340180-caed-11e8-9ba3-46ebb42f3bc2.png">

**Comment by mingzhouyang** [comment]
![image](https://user-images.githubusercontent.com/2938889/46620092-5811fd00-cb56-11e8-848c-0f6fb1039cc1.png)
