### ISSUE TITLE
Update formatting to be uniform on mobile search page

### ISSUE THREAD

**Issue by tiemaeroquerre** [ericmeltzer/proofofwork#18]
Make sure the bubbles and the font size are uniform - right now some are smaller than others
![img_8552](https://user-images.githubusercontent.com/32519583/46618670-311fe080-caee-11e8-815e-37f454f75359.PNG)

**Comment by mingzhouyang** [comment]
![image](https://user-images.githubusercontent.com/2938889/46619436-af16d280-cb54-11e8-8b62-e9cbdf880785.png)
This is the effect after the selection
