### ISSUE TITLE
Search shouldn't be case sensitive

### ISSUE THREAD

**Issue by tiemaeroquerre** [ericmeltzer/proofofwork#19]
Change the search function so that it is not case sensitive (for example: parity and Parity should yield the same results).

<img width="797" alt="screen shot 2018-10-08 at 4 00 21 pm" src="https://user-images.githubusercontent.com/32519583/46630921-caadb900-cb13-11e8-8a52-ae9e3fcc4bdd.png">
<img width="893" alt="screen shot 2018-10-08 at 4 00 34 pm" src="https://user-images.githubusercontent.com/32519583/46630922-cd101300-cb13-11e8-9c91-a2116b63d591.png">

**Comment by mingzhouyang** [comment]
Completed and put into production
