### ISSUE TITLE
Change color indicator for selection on Search Page

### ISSUE THREAD

**Issue by tiemaeroquerre** [ericmeltzer/proofofwork#20]
Selection of the type of search and ordering on the mobile search page should be indicated in blue. 
Current: 
![img_2170ef6d227d-1](https://user-images.githubusercontent.com/32519583/46631135-87077f00-cb14-11e8-9360-57782ca7007a.jpeg)
Change To:
<img width="394" alt="screen shot 2018-10-08 at 4 09 33 pm" src="https://user-images.githubusercontent.com/32519583/46631146-91c21400-cb14-11e8-886a-b23b873010b1.png">

**Comment by mingzhouyang** [comment]
completed
