### ISSUE TITLE
Make it so you can do "talk" threads where the link points to the comment thread

### ISSUE THREAD

**Issue by ericmeltzer** [ericmeltzer/proofofwork#8]
HN和lobsters都有‘讨论帖’，就是没有连接的thread。目前如果你submit一个没有连接的story，它的链接会是主页而不是帖子的链接。可以在URL的field下面放这个text：”Leave url blank to submit a question for discussion. If there is no url, your text description will appear at the top of the thread.
“

**Comment by ericmeltzer** [comment]
这个还不work。reproduce：submit一个新的story，没有url，如果从homepage观察的话，链接还是homepage的而不是story的

**Comment by shanhua** [comment]
![image](https://user-images.githubusercontent.com/652232/45999393-15710f00-c0d8-11e8-9e5e-ca03243c4428.png)
你使用的时候切换了分支，目前已经切换到master。链接已经指向了 story。
